services:
  - type: web
    name: spring-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d17on8adb0dc73dc8989-a:5432/immobilariadb_dlzs?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: immobiliariadb_dlzs_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 42K0HENhu2kU5781NkfNHnznmfcTqUtK
